### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by andreas-247** [ConnorLinfoot/TitleAPI#15]
I always get an error from simply sending a title to a player.
Code:
```
	@SuppressWarnings("deprecation")
	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String cmdlabel, String[] args) {
		
		Player p = (Player)sender;
		
		p.sendMessage("Message");
		TitleAPI.sendTitle(p, 40, 100, 20, "Title");
		
		return true;
	}
```
Error:
https://pastebin.com/r5yab0zZ

I think that I've not made any mistakes earlier because the message works just fine.

**Comment by andreas-247** [comment]
Version is spigot.1.12.2.

**Comment by ConnorLinfoot** [comment]
`Caused by: java.lang.ClassNotFoundException: com.connorlinfoot.titleapi.TitleAPI`

You don't seem to have TitleAPI included on the server.
