### ISSUE TITLE
Doesn't work in 1.10

### ISSUE THREAD

**Issue by ExZiByte** [ConnorLinfoot/TitleAPI#7]
The plugin doesn't load properly in 1.10
[http://pastebin.com/KS1qmqrA](url)

**Comment by ExZiByte** [comment]
also tested in 1.9 and 1.9.4 doesn't work in either

**Comment by ConnorLinfoot** [comment]
Works fine with Spigot 1.10.2.

**Comment by ExZiByte** [comment]
also doesnt work in 1.10.2 just tried it
same error
